name: quantum-robot-dev
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - black
  - pylint
  - coverage
  - "pytest>=5.4.3"
  - "dash>=2.0.0"
  - "matplotlib>=2.1.1"
  - "numpy>=1.18.5"
  - "pandas>=1.0.4"
  - "seaborn>=0.10.1"
  - "sphinx>=4.1.2"
  - "sphinx_rtd_theme>=0.5.0"
  - "ipykernel"
  - "nbsphinx>=0.8.6"
  - pip:
      - "qiskit>=0.30.1"
      - redis
